/** Onboarding strings — centralized until i18next (P0-12). */
export const onb = {
  appName: 'Fuel',
  tagline: 'The honest way to eat better — five seconds a meal.',
  bullet1: 'Scan, describe, or snap a label — done',
  bullet2: 'Targets that adapt to your real body',
  bullet3: 'A streak that survives busy days',
  apple: ' Sign in with Apple',
  google: 'Continue with Google',
  useEmail: 'Use email instead',
  restore: 'Restore purchase',
  emailTitle: 'Continue with email',
  emailSub: 'Sign in, or create your account — same box, we figure it out.',
  emailPh: 'you@example.com',
  passwordPh: 'Password (8+ characters)',
  working: 'Working…',
  continueBtn: 'Continue',
  goalTitle: 'What are we working toward?',
  goalSub: 'Your targets adapt every week from your own logs and weigh-ins — this just sets the starting point.',
  goalLose: 'Lose fat', goalLoseSub: 'Steady deficit, protein protected',
  goalBuild: 'Build muscle', goalBuildSub: 'Lean surplus, high protein',
  goalRecomp: 'Recomp', goalRecompSub: 'Hold weight, trade fat for muscle',
  goalHabit: 'Just eat better', goalHabitSub: 'No scale needed — build the habit first',
  aboutTitle: 'About you',
  aboutSub: "Four numbers — that's all the math needs. You can change any of them later.",
  female: 'Female', male: 'Male', other: 'Other',
  age: 'Age', height: 'Height', weight: 'Current weight',
  activityCaps: 'HOW ACTIVE ARE YOU, HONESTLY?',
  actSitting: 'Mostly sitting', actSittingSub: 'Desk job, little exercise',
  actLight: 'Lightly active', actLightSub: 'Walks + 1–3 workouts a week',
  actVery: 'Very active', actVerySub: 'Training 4+ days or physical job',
  aboutFootnote: "Don't stress the guess — after 2 weeks of logs we use your real burn, not this estimate.",
  planTitle: 'Your starting plan',
  planSub: (goal: string) =>
    goal === 'lose' ? 'Built for losing ~0.4 kg a week without losing muscle.'
    : goal === 'gain' ? 'Built for lean gaining without unnecessary fat.'
    : 'Built to hold steady while the habit forms.',
  kcalPerDay: 'KCAL / DAY',
  protein: 'Protein', carbs: 'Carbs', fat: 'Fat', water: 'Water',
  clampedNote: 'We raised this to a safe minimum of 1,200 kcal — health first.',
  planExplainer: "These aren't forever numbers. Every Sunday, Fuel compares your logs against your real weight change and recalibrates the plan to your body. The estimate only has to be roughly right.",
  reminderTitle: 'Daily reminder',
  reminderSub: "A nudge at 9 PM if the day's still empty", // TODO(stub): P3 notifications
  startDay1: 'Start Day 1',
  comingSoonTitle: 'Coming soon',
  comingSoonBody: 'Apple & Google sign-in arrive with store setup — use email for now.',
} as const;
