/** Today/Summary screen strings — centralized until i18next (P0-12). */
export const str = {
  summary: 'Summary',
  nutrition: 'Nutrition',
  onPace: 'On pace ›',
  overPace: 'Over ›',
  dayN: (n: number) => `Day ${n}`,     // B-17: real day number, not always "Day 1"
  calsLeft: 'Calories left',
  calsOver: 'Calories over',
  ofTarget: (n: string) => `of ${n}`,
  protein: 'Protein',
  carbsFat: 'Carbs · Fat',
  toGo: 'TO GO',
  // B-19: three DISTINCT states — they used to all be the one "Offline" pill.
  offline: 'No connection — your log is saved here',
  unsynced: (n: number) => `${n} entr${n === 1 ? 'y' : 'ies'} waiting to sync`,
  syncFailed: 'Sync failed — tap to retry',
  emptyHeadline: 'Log your first meal and the rings come alive.',
  emptyHint: 'Fastest ways: scan a barcode, or just type what you ate in plain words.',
  // A user with history is NOT a first-time user. Showing them "log your
  // first meal" after 40 logged days is the app forgetting who they are.
  emptyHeadlineReturning: 'Nothing logged yet today.',
  emptyHintReturning: 'Your usual foods are one tap away — the log sheet remembers them.',
  scanTitle: 'Scan your breakfast',
  scanSub: 'Any packaged food, 3 seconds',
  describeTitle: 'Or describe it',
  describeSub: '"2 idlis with sambar" — that\'s enough',
  streakStartTitle: 'Day 1 of your streak starts now',
  streakStartSub: 'Logging anything today counts',
  streakKeepTitle: (n: number) => `Keep your ${n}-day streak alive`,
  streakKeepSub: 'Logging anything today counts',
  streak: 'Streak',
  days: 'days',
  day: 'day',
  daysLongest: 'days · your longest',
  streakStart: 'Log today to start',
  streakToday: 'Logged today',
  streakAlive: 'Log today to keep it',
  water: 'Water',
  waterAdd: '+250',
  waterUndo: 'Undo',
  undoFailed: "Couldn't remove it from the server — restored. Try again online.",
  todaysMeals: "TODAY'S MEALS",
  removeTitle: 'Remove this entry?',
  removeBody: (name: string) => `"${name}" comes off today's log — everywhere, including the server.`,
  removeCta: 'Remove entry',
  removeFailedTitle: 'Not removed',
  removeFailedBody: "The server couldn't confirm the removal, so the entry was kept. Try again online.",
  weekAvg: (n: number) => `avg ${n.toLocaleString('en-US')} kcal`,
  trends: 'Trends',
  report: 'Report',
  tabSoon: 'Arrives in Phase 2, once you have a few weeks of logs to chart.',
} as const;
