/** Today/Summary screen strings — centralized until i18next (P0-12). */
export const str = {
  summary: 'Summary',
  nutrition: 'Nutrition',
  onPace: 'On pace ›',
  overPace: 'Over ›',
  day1: 'Day 1',
  calsLeft: 'Calories left',
  calsOver: 'Calories over',
  ofTarget: (n: string) => `of ${n}`,
  protein: 'Protein',
  carbsFat: 'Carbs · Fat',
  toGo: 'TO GO',
  offline: 'Offline — your log will sync',
  emptyHeadline: 'Log your first meal and the rings come alive.',
  emptyHint: 'Fastest ways: scan a barcode, or just type what you ate in plain words.',
  scanTitle: 'Scan your breakfast',
  scanSub: 'Any packaged food, 3 seconds',
  describeTitle: 'Or describe it',
  describeSub: '"2 idlis with sambar" — that\'s enough',
  streakStartTitle: 'Day 1 of your streak starts now',
  streakStartSub: 'Logging anything today counts',
  streak: 'Streak',
  days: 'days',
  daysLongest: 'days · your longest',
  water: 'Water',
  waterAdd: '+250',
  todaysMeals: "TODAY'S MEALS",
} as const;
